language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator10.0
before_install:
  - brew update
  - brew reinstall xctool
script:
  - xcodebuild -showsdks
  - xctool -workspace NextLevel.xcworkspace -scheme 'Debug - iOS' -sdk $IOS_SDK build analyze
